yarn:
 client:
  name: bdg
  priority: 0
  queue: default
  masterMemory: 128
  masterVirtualCores: 1
  keepContainerAcrossRestart: false
  debug: false
 am:
  name: bdg
 containerJar: /Users/adeelq/Documents/workspace-sts-3.6.3.SR1/yarnmailer/spring.jar
  